

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: madeiros-phpmyadmin
    restart: unless-stopped
    ports:
      - "8099:80"
    environment:
      PMA_HOST: madeiros-db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - madeiros

networks:
  madeiros:
    name: madeiros_madeiros
    external: true
